### PR TITLE
Stuff about a minimal C program

### PR DESCRIPTION
**Pull request by zhiming-qiu**
Basically a bit talk around a minimally authored C program for fun.

### CODE REVIEW

**Review by EachOneChew — APPROVED** [review]
We are just starting to learn about this in lectures.

>The main method returns an int to report the success of the program right? 

Yes

> Also, what is the difference between "$ ." and "$ ./"?

I am not aware of "$.". Where did you see it?

**Review by EachOneChew — APPROVED** [review]
>Edit: sometimes we seem to run things with ". file_name" but sometimes with "./ file_name". What's the distinction?

Good question. I think you are talking about "filename" vc "./filename".

Run via "filename" is like telling OS/shell "find the file according to a search strategy and run it". If search returns multiple files, take the first found.

Run via "./filename" is for telling OS only run the file found in current folder. (. refers to current folder)

**Comment by zhiming-qiu** [comment]
Environment variable PATH defines the search sites in order. For example, we have PATH as "/foo:/bar" and in both folder the file "a.out" exists.

 You are in folder "/bar". when you run "./a.out", it wil pick the one in bar. When running "a.out", it will pick the one in "/foo"

**Review by EachOneChew — APPROVED** [review]
Works

**Review by EachOneChew — APPROVED** [review]
Should work now

**Review by EachOneChew — APPROVED** [review]
Approved

**Pull request merged**
